language: java
install: true
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache/
before_script:
  - ./gradlew --version
  - cd ../..
  - git clone --depth=50 --branch=master https://github.com/jsr377/jsr377-api.git jsr377/jsr377-api
  - cd jsr377/jsr377-tck
script: ./gradlew --console=plain clean build --scan
env: TERM=dumb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d6db2c9eeb9719573e8
    on_success: change
    on_failure: always
    on_start: never
